openapi: 3.0.0
info:
  title: User & Avatar API
  version: v1
  description: |
    API for retrieving user information and avatars from Domo.
servers:
  - url: 'https://example.com/v1'
    description: Domo API
tags:
  - name: Users
    description: Retrieve information for one or all users.
  - name: Avatars
    description: Retrieve user avatar images.
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Access token obtained via Domo's authentication flow."
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: A human-readable error message.
          
    UserDetail:
      type: object
      description: Detailed information for a user.
      properties:
        title:
          type: string
        email:
          type: string
          format: email
        phoneNumber:
          type: string
        employeeNumber:
          type: integer
        pending:
          type: boolean
          
    User:
      type: object
      description: Represents a Domo user.
      properties:
        id:
          type: integer
          format: int64
        displayName:
          type: string
        avatarKey:
          type: string
          description: Path to the user's avatar image.
        role:
          type: string
        detail:
          $ref: '#/components/schemas/UserDetail'
          description: "Only present if 'includeDetails' is true."
          
  responses:
    NotFound:
      description: The requested resource was not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
            
security:
  - bearerAuth: []

paths:
  /domo/users/v1:
    get:
      summary: All Users
      description: Information for all users can be retrieved using this endpoint.
      tags: 
        - User API
      parameters:
        - name: includeDetails
          in: query
          description: Include all user information.
          schema:
            type: boolean
            default: false
        - name: limit
          in: query
          description: The number of user records to return.
          schema:
            type: integer
        - name: offset
          in: query
          description: Get users starting with this offset in the list of users.
          schema:
            type: integer
      responses:
        '200':
          description: A list of users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
              examples:
                DetailsFalse:
                  summary: includeDetails=false
                  value:
                    - id: 1
                      displayName: "User One"
                      avatarKey: "/domo/avatars/v1/avatars/dev/86/420BB31EE19FDDBA8096F19ACD4C4D.jpg"
                      role: "Admin"
                    - id: 3
                      displayName: "User Two"
                      avatarKey: "/domo/avatars/v1/avatars/dev/86/510BB31EE19FDDBA8046F18ACD3C5D.jpg"
                      role: "Privileged"
                DetailsTrue:
                  summary: includeDetails=true
                  value:
                    - id: 1
                      displayName: "User One"
                      avatarKey: "/domo/avatars/v1/avatars/dev/86/420BB31EE19FDDBA8096F19ACD4C4D.jpg"
                      role: "Admin"
                      detail:
                        title: ""
                        email: "userone@domo.com"
                        phoneNumber: ""
                        employeeNumber: 1
                        pending: false
                    - id: 2
                      displayName: "User Two"
                      avatarKey: "/domo/avatars/v1/avatars/dev/86/510BB31EE19FDDBA8046F18ACD3C5D.jpg"
                      role: "Privileged"
                      detail:
                        title: ""
                        email: "usertwo@domo.com"
                        phoneNumber: ""
                        employeeNumber: 2
                        pending: false
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /domo/users/v1/{userId}:
    get:
      summary: Single User
      description: Information for a single user can be retrieved using this endpoint.
      tags: 
        - User API
      parameters:
        - name: userId
          in: path
          required: true
          description: "The id (long) of the desired user."
          schema:
            type: integer
            format: int64
        - name: includeDetails
          in: query
          description: Include all user information.
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: A single user object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                DetailsFalse:
                  summary: includeDetails=false
                  value:
                    id: 1
                    displayName: "User One"
                    avatarKey: "/domo/avatars/v1/avatars/dev/86/420BB31EE19FDDBA8096F19ACD4C4D.jpg"
                    role: "Admin"
                DetailsTrue:
                  summary: includeDetails=true
                  value:
                    id: 1
                    displayName: "User One"
                    avatarKey: "/domo/avatars/v1/avatars/dev/86/420BB31EE19FDDBA8096F19ACD4C4D.jpg"
                    role: "Admin"
                    detail:
                      title: ""
                      email: "userone@domo.com"
                      phoneNumber: ""
                      employeeNumber: 1
                      pending: false
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          $ref: '#/components/responses/NotFound'

  /domo/avatars/v2/{entityType}/{entityId}:
    get:
      summary: User Avatar
      description: Retrieves the avatar image for a specific entity.
      tags: 
        - User API
      parameters:
        - name: entityType
          in: path
          required: true
          description: The type of entity.
          schema:
            type: string
            enum: [USER] # Based on the documentation
        - name: entityId
          in: path
          required: true
          description: The ID of the entity.
          schema:
            type: integer
            example: 846578099
        - name: size
          in: query
          description: "Valid sizes (pixels)"
          schema:
            type: integer
            enum: [100, 300]
        - name: defaultForeground
          in: query
          description: "Default text color if no avatar exists (e.g., 'fff')."
          schema:
            type: string
        - name: defaultBackground
          in: query
          description: "Default background color if no avatar exists (e.g., '000')."
          schema:
            type: string
        - name: defaultText
          in: query
          description: "Default text (initials) if no avatar exists (e.g., 'D')."
          schema:
            type: string
      responses:
        '200':
          description: The avatar image file.
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
            image/png:
              schema:
                type: string
                format: binary
            image/jpg:
              schema:
                type: string
                format: binary
        '404':
          $ref: '#/components/responses/NotFound'